<?php

/**
 * @file
 * Contains authorization.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function authorization_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the authorization module.
    case 'help.page.authorization':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Authorization API connects up providers (for example LDAP) with consumers (for example Organic Groups or Drupal roles).') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function authorization_theme() {
  $theme = [];

  return $theme;
}
