<?php

/**
 * @file
 * Contains authorization_drupal_roles.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function authorization_drupal_roles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the authorization_drupal_roles module.
    case 'help.page.authorization_drupal_roles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create Drupal roles as part of an Authorization workflow.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function authorization_drupal_roles_theme() {
  $theme = [];

  return $theme;
}
